services:
  db:
    image: postgres:16
    container_name: document-workflow-db
    environment:
      POSTGRES_DB: documents_db
      POSTGRES_USER: documents_user
      POSTGRES_PASSWORD: documents_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: document-workflow-rabbitmq
    # environment:
    #   RABBITMQ_DEFAULT_USER: rabbitmq_user
    #   RABBITMQ_DEFAULT_PASS: rabbitmq_password
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
