services:
  db:
    image: postgres:16
    container_name: document-workflow-db
    environment:
      POSTGRES_DB: documents_db
      POSTGRES_USER: documents_user
      POSTGRES_PASSWORD: documents_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
